#!/bin/bash
file=$HOME/entry-file
if [ -w $file ]
then
	date >> $file
	echo -n "Enter name of person or group: "
	read name
	echo "$name" >> $file
	echo >> $file
	cat >> $file
	echo "----------------------------" >> $file
	echo $file
else
	echo "You do not have the write permission to the file"
fi
